### ALGEBRA TASK

In [4]:
# Importing the necessary library
import numpy as np



### 3.1  Representing the data as a matrix
student 


In [5]:
# 3.1 Representing the data as a matrix
student= np.array([[80, 70, 90], [60, 85, 75], [95, 88, 92], [70,60,65]])
print(student)
print(student.shape)

[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]
(4, 3)


In [6]:
# 3.2 Total Scores per Student (Vector Addition)
student_1 = np.array([80, 70, 90])
sum_student_1 = np.sum(student_1)
student_2 = np.array([60, 85, 75]) 
sum_student_2 = np.sum(student_2)
student_3 = np.array([95, 88, 92])
sum_student_3 = np.sum(student_3)
student_4 = np.array([70, 60, 65])
sum_student_4 = np.sum(student_4)
print(f"Total Score for Student 1 is :", sum_student_1)
print(f"Total Score for Student 1 is :", sum_student_2)
print(f"Total Score for Student 1 is :", sum_student_3)
print(f"Total Score for Student 1 is :", sum_student_4)

Total Score for Student 1 is : 240
Total Score for Student 1 is : 220
Total Score for Student 1 is : 275
Total Score for Student 1 is : 195


In [7]:
# 3.3 Applying weights (Scalar multiplication)
scores =np.array([80, 60, 95, 70])

scaled_scores = scores * 2
print(scaled_scores)


[160 120 190 140]


```
Student     Math  English  Science 
Student 1   80      70      90 
Student 2   60      85      75 
Student 3   95      88      92 
Student 4   70      60      65 
 


In [8]:
# 3.4 Average Score per Subject (Matrix Operation)
math = np.array([80, 60, 95, 70])
math_avg = np.average(math)
print(f"Average Score for math is :", math_avg)

eng = np.array([70, 85, 88, 60])
eng_avg = np.average(eng)
print(f"The average score for English is :", eng_avg)

science = np.array([90, 75, 92, 65])
science_avg = np.average(science)
print(f"The average score for Science is:", science_avg)



Average Score for math is : 76.25
The average score for English is : 75.75
The average score for Science is: 80.5


In [13]:
# 3.5 Final Grades using Matrix Multiplication
student1 = np.array([80, 70, 90])
scalar_weight = np.array([0.5, 0.3, 0.2])
grade1 = (student1 * scalar_weight)
student2 = np.array([60, 85, 75])
grade2 = (student2 * scalar_weight)
student3 = np.array([95, 88, 92])
grade3 = (student3 * scalar_weight)
student_4 = np.array([70, 60, 65])
grade4 = np.sum(student1) / 3
print(f" The final grade for student 1 is :", grade1)
print(f" The final grade for student 2 is :", grade2)
print(f" The final grade for student 3 is :", grade3)
print(f" The final grade for student 4 is :", grade4)

 The final grade for student 1 is : [40. 21. 18.]
 The final grade for student 2 is : [30.  25.5 15. ]
 The final grade for student 3 is : [47.5 26.4 18.4]
 The final grade for student 4 is : 80.0


In [10]:
# 3.6 Comparing students (Vector Subtraction)

student1 = np.array([80, 70, 90])
student2 = np.array([60, 85, 75])
compared_grades = np.subtract(student1,student2)
print(f"The compared grade for student 1 and student 2 is :", compared_grades)

The compared grade for student 1 and student 2 is : [ 20 -15  15]


## ADD-ON EXERCISES

In [11]:
# 1. Create a new 5x3 matrix of scores (5 students, 4 subjects). Compute each sstudent's total score and the average per subject.