In [5]:
import numpy as np


# 1. Create a 6x6 Numpy array with random integers between 1 and 50. Display the array

new_array = np.random.randint(1, 50, (6,6))
new_array

array([[30, 16, 25, 26, 47,  7],
       [37, 33, 16,  8, 41, 19],
       [11,  5, 11, 19, 11, 29],
       [46, 43,  4, 36, 46, 36],
       [48, 18, 43, 13, 25, 22],
       [34, 30,  2, 13, 33, 42]], dtype=int32)

In [6]:
# 2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers.

# The first two rows
new_rows = new_array[0:2, 0:]
new_rows


array([[30, 16, 25, 26, 47,  7],
       [37, 33, 16,  8, 41, 19]], dtype=int32)

In [7]:
# The last three columns
new_column = new_array[0:, -3:] 
new_column

array([[26, 47,  7],
       [ 8, 41, 19],
       [19, 11, 29],
       [36, 46, 36],
       [13, 25, 22],
       [13, 33, 42]], dtype=int32)

In [17]:
# For all even numbers
even_numbers = new_array[new_array % 2 == 0]
even_numbers


array([30, 16, 26, 16,  8, 46,  4, 36, 46, 36, 48, 18, 22, 34, 30,  2, 42],
      dtype=int32)

# Question 3

In [9]:
# Perform the following array transformations:
# Reshape the array into a 3D(3, 2, 6) array.

new_shape = new_array.reshape(3,2,6)
new_shape

array([[[30, 16, 25, 26, 47,  7],
        [37, 33, 16,  8, 41, 19]],

       [[11,  5, 11, 19, 11, 29],
        [46, 43,  4, 36, 46, 36]],

       [[48, 18, 43, 13, 25, 22],
        [34, 30,  2, 13, 33, 42]]], dtype=int32)

In [10]:
# Flatten the reshaped array back to 1D
flat = new_shape.flatten()
flat

array([30, 16, 25, 26, 47,  7, 37, 33, 16,  8, 41, 19, 11,  5, 11, 19, 11,
       29, 46, 43,  4, 36, 46, 36, 48, 18, 43, 13, 25, 22, 34, 30,  2, 13,
       33, 42], dtype=int32)

# Question 4

In [11]:
# Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.diag(np.arange(10,50,10))

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

# Question 5

In [13]:
#Perform matrix multiplication between: A3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

matrix_1 = np.random.randint(1 , 10, (3,4))
matrix_2 = np.random.randint(1, 10, (4,3))
result = np.matmul(matrix_1, matrix_2)
print(result)

[[ 71  62  60]
 [170 101 122]
 [156 100 120]]


# Question 6

In [ ]:
# Create a function that takes a 2D Numpy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1

def main():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))

    arr = np.arange(rows * cols).reshape(rows,cols)
    new_arr = np.where(arr % 2 == 0, arr **2, -1)
    print(new_arr)
main()

