### **Understanding Numpy**

- Numpy (Numerical Python) is the foundation library for scientific computing in python. It provides N-dimensional array object and tools for working with these arrays.
- T hink of NumPy as the engine that powers most data science libraries - pandas uses NumPy arrarys internally, scikit-learn expects NumPy arrays for machine learning, and matplotlib uses NumPy for plotting.
- NumPy operations are implemented in C, making them 10-100x faster than pure Python.
- NumPy arrays store data more compactly than python lists.
- Vectorization: Perform operations on entire arrays without writing loops.
- Work with arrays of different shapes seamlessly.
- Foundation for pandas, scikit-learn, matplotlib, and more.

In [5]:
# import all necessary libraries

import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version 
print(f"Numpy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)



Numpy version: 2.3.2


* Creating Numpy Arrays

In [7]:
# Creating arrays from python lists
# ID array: A simple sequence of numbers
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1,2,3],
                  [4,5,6]])
#3D array: Like a stack of 2D arrays - useful for images. time series. etc.
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5,6], [7, 8]]])
print("1D arrays:", arr1d)
print("2D arrat:\n", arr2d)
print("3D array:\n", arr3d)

1D arrays: [1 2 3 4 5]
2D arrat:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Creating Special Arrays in Numpy

In [9]:
# Creating arrays filled with zeros - useful for initializing arrays
# Shape (3, 4) means 3 rows and 4 columns
zeros = np.zeros((3,4))

# Creating arrays filled with ones - often used as starting points
ones = np.ones((2, 3, 4))   #3D array: 2 layers, 3 rows, 4 columns

# Empty array - faster than zeros/ones bit contains random values
# Use when you'll immediately fill the array with real data
empty = np.empty((2, 2))

print("Zeros array (3x4):\n", zeros) 
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


In [10]:
# Range arrays - like python's range() but more powerful
range_arr = np.arange(0, 10, 2)  # Start, Stop, Step: [0, 2, 4, 6, 8]
print("Range array:", range_arr)

# Linearly spaced arrays - divide a range into equal parts 
# From 0 to 1 with exactly 5 points ( including endpoints)
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

#Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [11]:
# Identity matrix - diagonal ones, zeros elsewhere
# Essential for linear algebra operations
identity = np.eye(4)  # 4x4 identity matrix

# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1, 2, 3, 4])

# Array filled with a specific value
full_arr = np.full((3, 3), 7)   # 3x3 array filled with 7

print("Identity matrix:\n", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


#### Numpy Data Types (dtypes)

In [12]:
# Explicit data types - control memory usage and precision
int_arr = np.array([1, 2, 3], dtype=np.int32)   # 32-bit integers
float_arr = np.array([1, 2, 3], dtype=np.float64)  # 64-bit floats (double precision)
bool_arr = np.array([True, False, True], dtype=np.bool_)   # boolean values

# Type conversion - change dtype of wxisting array
converted = int_arr.astype(np.float32)   # convert to 32-bit float
 
print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:",float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)

# Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element


In [ ]:
# Create a sample 3D array for demonstration
# Think of this as a 3 layers, each with 4 rows and 5 columns
arr = np.random.randn(3, 4, 5)

# Shape: The dimensions of the array (layers, rows, columns)
print("Shape:", arr.shape)   # Output: (3, 4, 5)

# Size: Total number of elements (3 x 4 x 5 = 60)
print("Size:", arr.size)

#Ndim: Number of dimensions (3D in this case)
print("Ndim:", arr.ndim)

#