### **Understanding Numpy**

- Numpy (Numerical Python) is the foundation library for scientific computing in python. It provides N-dimensional array object and tools for working with these arrays.
- T hink of NumPy as the engine that powers most data science libraries - pandas uses NumPy arrarys internally, scikit-learn expects NumPy arrays for machine learning, and matplotlib uses NumPy for plotting.
- NumPy operations are implemented in C, making them 10-100x faster than pure Python.
- NumPy arrays store data more compactly than python lists.
- Vectorization: Perform operations on entire arrays without writing loops.
- Work with arrays of different shapes seamlessly.
- Foundation for pandas, scikit-learn, matplotlib, and more.

In [1]:
# import all necessary libraries

import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version 
print(f"Numpy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)



Numpy version: 2.3.3


* Creating Numpy Arrays

In [3]:
# Creating arrays from python lists
# ID array: A simple sequence of numbers
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1,2,3],
                  [4,5,6]])
#3D array: Like a stack of 2D arrays - useful for images. time series. etc.
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5,6], [7, 8]]])
print("1D arrays:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D arrays: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Creating arrays filled with zeros - useful for initialization arrays 
# Shape (3, 4) means 3 rows and 4 columns
zeros = np.zeros((3, 4))

# Creating arrays filled with ones - often used as starting points
ones = np.ones((2,3,4))     # 3D array: 2 layers, 3 rows, 4 columns

# Empty array - faster than zero/ones bit contain random values
# Use when you'll immediately fill the array with real data
empty = np.empty((2, 2))

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)