# CLASS TASK 2

__1. Identify the number of rows and columns in each matrix.__

__Matrix A__  

Rows - 2
Columns - 3

The order is 2 by 3


__Matrix B__
 
Rows - 3
Columns - 2

The order is 3 by 2

In [1]:
# using numpy for numerical operations
import numpy as np
# creating matrix A array which is a 2x3 matrix
A = np.array([[2, -1, 3], 
              [0, 4, 1]])

# creating matrix B array which is a 3x2 matrix
B = np.array([
             [1, 2],
             [-2, 0],
             [2, -3]])

# identify the number of rows and columns in matrix A:
print("Matrix A (2x3):",  A)
print("Shape:", A.shape)

# identify the number of rows and columns in matrix B:
print("Matrix B: (3x2)", B)
print("Shape:", B.shape)

Matrix A (2x3): [[ 2 -1  3]
 [ 0  4  1]]
Shape: (2, 3)
Matrix B: (3x2) [[ 1  2]
 [-2  0]
 [ 2 -3]]
Shape: (3, 2)


__2. Determine whether the matrices can be multiplied. If so, specify whether it's (AB),(BA), or both.__

The number of rows in matrix A is equal to the number of columns in matrix B, this makes them compatible for multiplication.
A = 2x3
B = 3x2
In this case the AB multiplication can be multiplied.

The number of number of rows in matrix B is equal to the number of columns in matrix A which also makes it possible for multiplication.

Multiplication in matrices are not commutative which means the result of AB is not equal to BA as AB!= BA.

3. __If the multiplication is defined, compute the resulting matrix.__
For matrix AB:

A = np.array([[2,-1,3],
              [0,4,1]])
B = np.array([[1,2],
              [-2,0],
              [5,-3]])

              

AB = Row 1 column 1             Row 1 column 2
     [(2*1)+(-1*-2)+(3*5)]    [(2*2)+(-1*0)+(3*-3)]

    Row 2 column 1              Row 2 column 2
    [(0*1)+(4*-2)+(1*5)]        [(0*2)+(4*0)+(1*-3)]



AB = [(2+2+15), (4+0+(-9))
      (0+(-8)+5), (0+0+(-3))]


AB = [[19, -5],
      [-3, -3]]


The resulting order for matrix AB is (2*2) matrix.



For matrix BA:
B = np.array([[1,2],
             [-2,0],
             [5,-3]])


A = np.array([[2,-1,3]
              [0,4,1]])



BA = row 1 column 1     row 1 column 2      row 1 column 3
    [(1*2)+(2*0)]       [(1*-1)+(2*4)]      [(1*3)+(2*1)]
    row 2 column 1      row 2 column 2      row 3 column 3
    [(-2*2)+(0*0)]      [(-2*-1)+(0*4)]     [(-2*3)+(0*1)]
    row 3 column 1      row 3 column 2      row 3 column 3
    [(5*2)+(-3*0)]      [(5*-1)+(-3*4)]     [(5*3)+(-3*1)]



BA = [(2),(7),(5),
      (-4),(-2),(-6),
      (10),(-17),(12)]


BA = [[2,7,5],
      [-4,2,-6],
      [10,-17,12]]

      
The resulting order for matrix BA is (3*3) matrix.


In [3]:
A = np.array([[2, -1, 3], 
              [0, 4, 1]])


B = np.array([
             [1, 2],
             [-2, 0],
             [5, -3]])

# For matrix AB:
AB = A @ B
print("Matrix AXB =\n", AB)
print("Shape:", AB.shape)

Matrix AXB =
 [[19 -5]
 [-3 -3]]
Shape: (2, 2)


In [5]:
A = np.array([[2, -1, 3], 
              [0, 4, 1]])


B = np.array([
             [1, 2],
             [-2, 0],
             [5, -3]])

# For matrix BA:
BA = B @ A
print("Matrix BXA =\n", BA)
print("Shape:", BA.shape)

Matrix BXA =
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
Shape: (3, 3)
