### ALGEBRA TASK

In [4]:
# Importing the necessary library
import numpy as np



In [5]:
# 3.1 Representing the data as a matrix
student= np.array([[80, 70, 90], [60, 85, 75], [95, 88, 92], [70,60,65]])
print(student)
print(student.shape)

[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]
(4, 3)


In [6]:
# 3.2 Total Scores per Student (Vector Addition)
student_1 = np.array([80, 70, 90])
sum_student_1 = np.sum(student_1)
student_2 = np.array([60, 85, 75]) 
sum_student_2 = np.sum(student_2)
student_3 = np.array([95, 88, 92])
sum_student_3 = np.sum(student_3)
student_4 = np.array([70, 60, 65])
sum_student_4 = np.sum(student_4)
print(f"Total Score for Student 1 is :", sum_student_1)
print(f"Total Score for Student 2 is :", sum_student_2)
print(f"Total Score for Student 3 is :", sum_student_3)
print(f"Total Score for Student 4 is :", sum_student_4)

Total Score for Student 1 is : 240
Total Score for Student 2 is : 220
Total Score for Student 3 is : 275
Total Score for Student 4 is : 195


In [7]:
# 3.3 Applying weights (Scalar multiplication)
scores =np.array([80, 60, 95, 70])

scaled_scores = scores * 2
print(scaled_scores)


[160 120 190 140]


```
Student     Math  English  Science 
Student 1   80      70      90 
Student 2   60      85      75 
Student 3   95      88      92 
Student 4   70      60      65 
 


In [8]:
# 3.4 Average Score per Subject (Matrix Operation)
math = np.array([80, 60, 95, 70])
math_avg = np.average(math)
print(f"Average Score for math is :", math_avg)

eng = np.array([70, 85, 88, 60])
eng_avg = np.average(eng)
print(f"The average score for English is :", eng_avg)

science = np.array([90, 75, 92, 65])
science_avg = np.average(science)
print(f"The average score for Science is:", science_avg)



Average Score for math is : 76.25
The average score for English is : 75.75
The average score for Science is: 80.5


In [9]:
# 3.5 Final Grades using Matrix Multiplication
student1 = np.array([80, 70, 90])
scalar_weight = np.array([0.5, 0.3, 0.2])
grade1 = (student1 * scalar_weight)
student2 = np.array([60, 85, 75])
grade2 = (student2 * scalar_weight)
student3 = np.array([95, 88, 92])
grade3 = (student3 * scalar_weight)
student4 = np.array([70, 60, 65])
grade4 = (student4 * scalar_weight)
print(f" The final grade for student 1 is :", grade1)
print(f" The final grade for student 2 is :", grade2)
print(f" The final grade for student 3 is :", grade3)
print(f" The final grade for student 4 is :", grade4)

 The final grade for student 1 is : [40. 21. 18.]
 The final grade for student 2 is : [30.  25.5 15. ]
 The final grade for student 3 is : [47.5 26.4 18.4]
 The final grade for student 4 is : [35. 18. 13.]


In [10]:
# 3.6 Comparing students (Vector Subtraction)

student1 = np.array([80, 70, 90])
student2 = np.array([60, 85, 75])
compared_grades = np.subtract(student1,student2)
print(f"The compared grade for student 1 and student 2 is :", compared_grades)

The compared grade for student 1 and student 2 is : [ 20 -15  15]


## ADD-ON EXERCISES

In [11]:
# 1. Create a new 5x3 matrix of scores (5 students, 4 subjects). Compute each student's total score and the average per subject. Subjects are: maths, English, Science, P.H.E
students = np.array([[65, 80, 95, 55], [60, 72, 88, 90], [72, 75, 98, 85], [80, 78, 76, 80],[65, 95, 80, 68]])

print("Students:")
print(students)

Students:
[[65 80 95 55]
 [60 72 88 90]
 [72 75 98 85]
 [80 78 76 80]
 [65 95 80 68]]


 1. Create a new 5x3 matrix of scores (5 students, 4 subjects). Compute each student's total score and the average per subject. Subjects are: maths, English, Science, P.H.E
students = np.array
\begin{bmatrix}
students & Maths & English & Science & P.H.E\\
    student1 & 65 & 80 & 95 & 55\\
    student2 & 60 & 72 & 88 & 90 \\
    student3 & 72 & 75 & 98 & 85 \\
    student4 & 80 & 78 & 76 & 80 \\
    student5 & 65 & 95 & 80 & 68 \\
\end{bmatrix}
    



In [12]:
# 1.1 Student's total score
students_1_sum= np.sum([65, 80, 95, 55])
students_2_sum = np.sum([60, 72, 88, 90])
students_3_sum = np.sum([72, 75, 98, 85])
students_4_sum = np.sum([80, 78, 76, 80])
students_5_sum = np.sum([65, 95, 80, 68])
print(f" Student 1 total score is :",students_1_sum)
print(f" Student 2 total score is :",students_2_sum)
print(f" Student 3 total score is :",students_3_sum)
print(f" Student 4 total score is :",students_4_sum)
print(f" Student 5 total score is :",students_5_sum)

 Student 1 total score is : 295
 Student 2 total score is : 310
 Student 3 total score is : 330
 Student 4 total score is : 314
 Student 5 total score is : 308


\begin{bmatrix}
65&80&95&55\\
60&72&88&90 \\
72&75&98&85 \\
80&78&76&80 \\
65&95&80&68 \\
\end{bmatrix}
    

In [13]:
# 1.2 Average score per subject
maths_avg = np.average([65,60,72,80,65])
engl_avg = np.average([80,72,75,78,95])
sci_avg = np.average([95,88,98,76,80])
avg_phe = np.average([55,90,85,80,68])
print(f"Average maths score:", maths_avg)
print(f"Average English score:",  engl_avg)
print(f"Average Science score:", sci_avg)
print(f"Average P.H.E Score:", avg_phe)

Average maths score: 68.4
Average English score: 80.0
Average Science score: 87.4
Average P.H.E Score: 75.6


In [14]:
# 2. Suppose one subject is (e.g science) is 3 times more important than others. Apply scalar multiplication and recompute totals.
science_matrix = np.array([95,88,98,76,80])
total = science_matrix * 3
total

array([285, 264, 294, 228, 240])

In [15]:
# 3. Define new weights for grading (40%, 20%, 30%, 10%). Compute final grades using matrix multiplication.
weights = np.array([0.4, 0.2, 0.3, 0.1])
final_grades = students @ weights
final_grades

array([76. , 73.8, 81.7, 78.4, 75.8])

In [16]:
# 4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subject?

third_student = students[2]
fourth_student = students[3]

compared_scores = np.subtract(third_student,fourth_student)
compared_scores

array([-8, -3, 22,  5])