In [9]:
import numpy as np

Let A = [[2,-1],
        [0,3]]

Let B = [[1,4],
         [-2,5]]

Let scalar (c = 2), (d = 3)


* 1. Compute the following: (cA), (dB), and (c + d)A
* 2. Using the results gotten, Verify the scalar multiplication properties.
* 3. Find the transpose of both matrices:
* 4. Check if (A) and (B) are invertible by computing their determinants. If they are invertible, find: A-1 and B-1.

Compute the following: (cA), (dB), and (C+d)A
```

A = [2   -1]    [0  3]


B = [1  4]      [-2 5]

scalar c = 2, d = 3

In [ ]:
A = np.array([[2,-1],[0,3]])
B = np.array([[1,4],[-2,5]])
c = 2
d = 3
print(f"A = ", A)
print(f"B = ", B)

A =  [[ 2 -1]
 [ 0  3]]
B =  [[ 1  4]
 [-2  5]]


In [ ]:
# The result of the scalar multiplication cA is:
cA = c * A
print(cA)

[[ 4 -2]
 [ 0  6]]


In [19]:
# The result of the scalar multiplication dB is:
dB = d * B
print(dB)

[[ 3 12]
 [-6 15]]


In [20]:
# The result of (c+d)A is:
ass_dist  = np.sum(c +d ) * A
print(ass_dist)

[[10 -5]
 [ 0 15]]


### 2.Using the result gotten, verify the scalar multiplication properties.

In [24]:
# Associativity of scalar matrix (c.d)A = c.(dA)
left = (c*d)*A
right = c*(d*A)
print(f"Associative property:")
print(f"(c.d)A = c(dA): {np.array_equal(left, right)}")


Associative property:
(c.d)A = c(dA): True


In [ ]:
# Distributivity over matrix addition c(A + B) = cA + cB
new_left = c*(A + B)
new_right = (c*A) + (c*B)
print(f"Distributive property:")
print(f"c(A+B)) = (c.A)+(c.B): {np.array_equal(new_left, new_right)}") 

Distributive property:
c(A+B)) = (c.A)+(c.B): True


In [28]:
# Distributivity over scalar addition (c+d)A = cA + dA
left_new = (c + d) * A
right_new = (c*A) + (d*A)
print(f"Distributivity over scalar addition property:")
print(f"(c+d)A = (c.A) + (d.A): {np.array_equal(left_new, right_new)}")

Distributivity over scalar addition property:
(c+d)A = (c.A) + (d.A): True


In [29]:
# 3. Find the transpose of both matrices
print("Matrix A:", A)
print("Transpose A^T:", A.T)
print("Matrix B:", B)
print("Transpose B^T:", B.T)

Matrix A: [[ 2 -1]
 [ 0  3]]
Transpose A^T: [[ 2  0]
 [-1  3]]
Matrix B: [[ 1  4]
 [-2  5]]
Transpose B^T: [[ 1 -2]
 [ 4  5]]


In [34]:
# 4. Find the inverse of both matrices
print(A)
print("Determinant of A:", np.linalg.det(A))
print("Inverse of A:", np.linalg.inv(A))

print(B)
print("Determinant of B:", np.linalg.det(B))
print("Inverse of B:", np.linalg.inv(B))


[[ 2 -1]
 [ 0  3]]
Determinant of A: 6.0
Inverse of A: [[0.5        0.16666667]
 [0.         0.33333333]]
[[ 1  4]
 [-2  5]]
Determinant of B: 13.0
Inverse of B: [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
